# Generated by Django 3.0.8 on 2020-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='эл. адрес')),
                ('subject', models.CharField(max_length=100, verbose_name='тема вопроса')),
                ('message', models.TextField(verbose_name='текст')),
            ],
            options={
                'verbose_name': 'Сообщение от пользователя',
                'verbose_name_plural': 'Сообщения пользователей',
            },
        ),
    ]
